### ISSUE TITLE
Support multiple waste types for today and tomorrow sensor

### ISSUE THREAD

**Issue by Sholofly** [xirixiz/home-assistant#1]
Sometimes, multiple waste types are being picked up on the same date. The today and tomorrow sensor only support the first waste type in the API. It would be nice when the sensors are showing all waste types on the same date (i.e. comma-separated).

I've tried to create a fork and change the code myself. But I;m lacking a sufficient python development environment. Besides that my python skills are not that great ;)

**Comment by xirixiz** [comment]
A bit late...but I`ll look into this :).

**Comment by xirixiz** [comment]
Hi, 

I just created version 1.1.5 with this feature. Cheers!
https://github.com/xirixiz/home-assistant-config/issues/3

**Comment by Sholofly** [comment]
brillianr. thanks!

Op vr 7 dec. 2018 16:34 schreef Bram van Dartel <notifications@github.com:
