### ISSUE TITLE
Create PiPy Package to enable  integration in Home Assistant Installation

### ISSUE THREAD

**Issue by Sholofly** [xirixiz/home-assistant#2]
It would be nice if the Afvalwijzer component could be wrapped up in a PiPyPackage, It's one of the requirements to get this sensor in the default Home Assistant integration.

See: https://developers.home-assistant.io/docs/en/creating_platform_code_review.html

**Comment by xirixiz** [comment]
I tried to get this package as a default Home Assistant integration, but it was refused. The value of this component is to narrow/specific for a region. It should be more generic.

**Comment by Sholofly** [comment]
Sounds realistic. Thanks for trying.
